name: UniversalSkins
main: ru.ruscalworld.universalskins.UniversalSkins
author: RuscalWorld
version: ${version}
softdepend:
    - PosePlugin
api-version: 1.16
commands:
    skin:
        description: Main command